<?php /* Copyright 2011-2013 Braiins Ltd

/bdt/apps/CFD/CFDDL.php

Download file generated by CFD.php for FS Downloads.
File is deleted after the download.

History:
10.02.12 Started
19.10.12 Updated

*/

$AppAid  = 'CFD';
$AppName = 'FS Download';
require '../../BaseMin.inc';
$AppEnum = BDT_CFD;
require Com_Inc.'FuncsBraiins.inc';  # for UpdateEntity() at the end

if (isset($_POST['Dat']))
  LogIt('CFDDL.php _POST[Dat]='.$_POST['Dat']); # |
else
  LogIt('CFDDL.php No _POST[Dat]'); # |

if (isset($_POST['Dat']) && (count($DatA = explode('', $_POST['Dat'])) == 3)) {
  $file     = $DatA[0];      # relative to Braiins/Out/
  $EntityId = (int)$DatA[1];
  $FormatId = (int)$DatA[2];
}else
  exit;
header('Content-Type: text/html; charset=UTF-8');
header('Content-Disposition: attachment; filename="'.$file.'.htm"');
$file = "../../../../Out/$file";
header('Content-Length:'.filesize($file));
readfile($file);
flush();
unlink($file);

# Add Entity Trans for the download and update AcctsState for a statutory format if required
# Get Entity Info
$EA = $DB->AaQuery("Select CurrYear,AcctsState From Entities Where Id=$EntityId");
extract($EA); # -> $CurrYear, $AcctsState
if ($DB->OneQuery("Select FTypeN From Formats Where Id=$FormatId")==RGFT_Stat) {
  # Statutory format so update $AcctsState for the Download if not set
  $AcctsState = (int)$AcctsState;
  if (!($AcctsState & EASB_Down)) {
    $AcctsState |= EASB_Down;
    $DB->autocommit(false);
    UpdateEntity($EntityId, 'AcctsState', $AcctsState, $EA);
    AddEntityTran($EntityId, $CurrYear, BDT_CFD, ETA_RgDown, $FormatId, ETA_SetAcctsState, $AcctsState);
    $DB->commit();
  }else # EASB_Down is set so just the download tran
    AddEntityTran($EntityId, $CurrYear, BDT_CFD, ETA_RgDown, $FormatId);
}else # not a stat format so just the download tran
  AddEntityTran($EntityId, $CurrYear, BDT_CFD, ETA_RgDown, $FormatId);
